services:
  client:
    image: ge0lavz/ds-ui-lib-client
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  storybook:
    image: ge0lavz/ds-ui-lib-storybook
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    environment: 
      - NODE_ENV=development
    command: npm run storybook