/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DesignSystemImport } from './routes/design-system'
import { Route as ComponentLibraryImport } from './routes/component-library'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DesignSystemRoute = DesignSystemImport.update({
  path: '/design-system',
  getParentRoute: () => rootRoute,
} as any)

const ComponentLibraryRoute = ComponentLibraryImport.update({
  path: '/component-library',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/component-library': {
      id: '/component-library'
      path: '/component-library'
      fullPath: '/component-library'
      preLoaderRoute: typeof ComponentLibraryImport
      parentRoute: typeof rootRoute
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ComponentLibraryRoute,
  DesignSystemRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/component-library",
        "/design-system"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/component-library": {
      "filePath": "component-library.tsx"
    },
    "/design-system": {
      "filePath": "design-system.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
